game_names = [
    "Borderlands 3",
    "Outer Wilds",
    "Hollow Knight",
    "Cocoon",
    "Dredge",
    "Tunic",
    "Pentiment",
    "Risk of Rain 2",
    "God of War 4",
    "Marvel's Spider-Man: Game of the Year Edition",
    "Marvel's Spider-Man: Miles Morales",
    "Marvel's Spider-Man 2",
    "Red Dead Redemption II",
    "Horizon Zero Dawn",
    "Doom Eternal",
    "The Last of Us Part I",
    "The Last Of Us 2",
    "Elden Ring",
    "A Plague Tale: Innocence",
    "A Plague Tale: Requiem",
    "Cyberpunk 2077: Ultimate Edition",
    "Until Dawn",
    "Alan Wake Remastered",
    "Control",
    "Mass Effect Legendary Edition",
    "Hi-Fi Rush",
    "Star Wars Jedi: Survivor",
    "Alan Wake 2",
    "Uncharted 4: A Thief's End",
    "The Outer Worlds: Spacer's Choice Edition",
    "High On Life",
    "Ratchet & Clank",
    "Grounded",
    "Deep Rock Galactic",
    "Resident Evil 2",
    "Resident Evil 4",
    "Hogwarts Legacy",
    "Armored Core VI: Fires of Rubicon",
    "Dead Space (2023)",
    "Horizon Forbidden West",
    "Lies of P",
    "Returnal",
    "Stray",
    "Into the Breach",
    "Jusant",
    "God of War: Ragnarok",
    "Ghost of Tsushima",
    "Bloodborne",
    "Shadow of the Colossus",
    "Psychonauts 2",
    "SOMA",
    "Chorus",
    "ŌKAMI",
    "What Remains of Edith Finch",
    "Mortal Shell",
    "Gone Home",
    "Venba",
    "Citizen Sleeper",
    "Transistor",
    "Subnautica",
    "Slay The Princess",
    "Wildermyth",
    "Baba is You",
    "Return of the Obra Dinn",
    "Nobody Saves the World",
    "Slay the Spire",
    "Roboquest",
    "Robocop: Rogue City",
    "Pyre",
    "Bastion",
    "Metal Gear Solid V: Phantom Pain",
    "Marvel's Guardians of the Galaxy",
    "Mullet Mad Jack",
    "Spiritfarer: Farewell Edition",
    "Baldur's Gate 3",
    "Pony Island",
    "Faster than Light",
    "Minishoot' Adventures",
    "Balatro",
    "Hotline Miami"
]